# Generated by Django 3.2.9 on 2021-12-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pychiatrist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NMC', models.IntegerField()),
                ('Name', models.CharField(max_length=40)),
                ('Qualification', models.CharField(max_length=40)),
                ('Speciality', models.CharField(max_length=40)),
            ],
        ),
    ]
